sudo: required
services:
  - docker
language: bash
script:
  - make compile_and_test
  - make deb_arm
deploy:
  - provider: releases
    api_key:
      secure: Jo26CP/4QNUbMOYHc799pewxu8x87lBJMH/omlf9GHa6v4A4mMeVMayJZU+DKojHvrsbPk4CiaBk7DsxXi5Rzw9s5szHm+oTJKfdFp7LjncV+AZY+KYWhcjgyeLBPW3xNFPNUucosIk+y50Uh2EaEh1j7yys2o8/yviw/14rpW/RI+YJPyT+dg1jwzkgkq9xJZc8GhMjJNQzTRhveGcXB8INF7eoZzICXzkWyysYDreBZx4QDCpVk2RMzGsHqhQSdjgyDjaqCQTm7yZXDNzH4KEcwcOFTKrfhdqy0fq226pIpxqPgjjU+9ceDUGxsiltUco1U+96eiGABSHBCSod5UX+BqcHb3zgdxk9SMfrq51UEQweGMIUV5EZ/gqxBbQmIGwc8/mWtC7++tVCtfCQpJLUHxlD5j6Iasittyy82GVqSx2b+LPRfWjVSWfGS7iezkayjjknbT7CSSDgY507VWFecPu/XbojNG0PPswG/6hjNS1cgqgztaJK/u/ZI1wFI/F3aMaRJVJzb7YPAvGJaJ/J3BsZslueG41vnBP6+d1bXzUW984s/U3ZO220KAUCIvMR7wlvGvMkq6JVkTW5JkOvrZ78Da8T54vp5BxC4HTLkQyGXMtZ0SFPWJTLOinMXq/XEDmlds1K70ORKVPGibmxLeEW3gfu4KxuZflKFbk=
    file_glob: true
    skip_cleanup: true
    file:
      - device-init-*-armhf.deb
      - device-init_linux_arm
      - device-init_linux_amd64
    on:
      tags: true
      repo: hypriot/device-init
  - provider: packagecloud
    repository: "Schatzkiste"
    username: "Hypriot"
    token:
      secure: "jrAcpyT30EvFhvcePM/D2ty3hUQFHPJa7A5zmMUMh9klXPCJn4bj58b1oxl08iC3/oTokLOOAh2Php0w/FujlXgVEg4oDX9JE0pfV+YIwwILB8aHuB1C8sYSdkWXHk0nYfM2bJNHSVt96e3ONHWmpyVXovKa5eDF/gc+sihtOx6mBqwdwVVrBH9nMWlUTlAnyKSEgSU3gf1U1iS6IkAhVCFjmBckMKj/Td0ayK2+Qh/0gToTjpoBE7H+o46Ix8pO2VxVt9hvBRkIjsFWfJWaGL+mj9ww7kR+B7BYbxPSoWD09olMGqMJQ+lPVwND/mU7S6XEfSglBLgvriRQ6Ysg1wOc19aQVGPN1Q4I4Bv7qcSRDubVXaRVxeCaDozYkdyWYUv3VHxbuSFOtlwUj4t6sCwqjKYvCsNP3hLZEemrM38tn+goMDl5a0UNJANMWFyaeni7LT3CTaWJNPLfk0fn6yoTUngsTJSk01MWvw/eDRWcJPHHoMkibDoJ13EOHISgUIBV2HfCuuvZTa/d6c/TSKw5oKxGxgyi4U5kaEaX3NX2a/6cLS3Ishxm9f+g+4cFfZlQh1wCm+S1FhWfBe+Q0qVwtJZJg5mSgF6sTcyKlem5Ib3qdho7t+9fZ4Qhy7ZUPIweL/y3HIiOldwH2CW9hSm69S/aWEmRAjcF1m/juKA="
    package_glob: *.deb
    dist: "debian/wheezy"
    on:
      tags: true
  - provider: packagecloud
    repository: "Schatzkiste"
    username: "Hypriot"
    token:
      secure: "jrAcpyT30EvFhvcePM/D2ty3hUQFHPJa7A5zmMUMh9klXPCJn4bj58b1oxl08iC3/oTokLOOAh2Php0w/FujlXgVEg4oDX9JE0pfV+YIwwILB8aHuB1C8sYSdkWXHk0nYfM2bJNHSVt96e3ONHWmpyVXovKa5eDF/gc+sihtOx6mBqwdwVVrBH9nMWlUTlAnyKSEgSU3gf1U1iS6IkAhVCFjmBckMKj/Td0ayK2+Qh/0gToTjpoBE7H+o46Ix8pO2VxVt9hvBRkIjsFWfJWaGL+mj9ww7kR+B7BYbxPSoWD09olMGqMJQ+lPVwND/mU7S6XEfSglBLgvriRQ6Ysg1wOc19aQVGPN1Q4I4Bv7qcSRDubVXaRVxeCaDozYkdyWYUv3VHxbuSFOtlwUj4t6sCwqjKYvCsNP3hLZEemrM38tn+goMDl5a0UNJANMWFyaeni7LT3CTaWJNPLfk0fn6yoTUngsTJSk01MWvw/eDRWcJPHHoMkibDoJ13EOHISgUIBV2HfCuuvZTa/d6c/TSKw5oKxGxgyi4U5kaEaX3NX2a/6cLS3Ishxm9f+g+4cFfZlQh1wCm+S1FhWfBe+Q0qVwtJZJg5mSgF6sTcyKlem5Ib3qdho7t+9fZ4Qhy7ZUPIweL/y3HIiOldwH2CW9hSm69S/aWEmRAjcF1m/juKA="
    package_glob: *.deb
    dist: "debian/jessie"
    on:
      tags: true
  - provider: packagecloud
    repository: "Schatzkiste"
    username: "Hypriot"
    token:
      secure: "jrAcpyT30EvFhvcePM/D2ty3hUQFHPJa7A5zmMUMh9klXPCJn4bj58b1oxl08iC3/oTokLOOAh2Php0w/FujlXgVEg4oDX9JE0pfV+YIwwILB8aHuB1C8sYSdkWXHk0nYfM2bJNHSVt96e3ONHWmpyVXovKa5eDF/gc+sihtOx6mBqwdwVVrBH9nMWlUTlAnyKSEgSU3gf1U1iS6IkAhVCFjmBckMKj/Td0ayK2+Qh/0gToTjpoBE7H+o46Ix8pO2VxVt9hvBRkIjsFWfJWaGL+mj9ww7kR+B7BYbxPSoWD09olMGqMJQ+lPVwND/mU7S6XEfSglBLgvriRQ6Ysg1wOc19aQVGPN1Q4I4Bv7qcSRDubVXaRVxeCaDozYkdyWYUv3VHxbuSFOtlwUj4t6sCwqjKYvCsNP3hLZEemrM38tn+goMDl5a0UNJANMWFyaeni7LT3CTaWJNPLfk0fn6yoTUngsTJSk01MWvw/eDRWcJPHHoMkibDoJ13EOHISgUIBV2HfCuuvZTa/d6c/TSKw5oKxGxgyi4U5kaEaX3NX2a/6cLS3Ishxm9f+g+4cFfZlQh1wCm+S1FhWfBe+Q0qVwtJZJg5mSgF6sTcyKlem5Ib3qdho7t+9fZ4Qhy7ZUPIweL/y3HIiOldwH2CW9hSm69S/aWEmRAjcF1m/juKA="
    package_glob: *.deb
    dist: "raspbian/wheezy"
    on:
      tags: true
  - provider: packagecloud
    repository: "Schatzkiste"
    username: "Hypriot"
    token:
      secure: "jrAcpyT30EvFhvcePM/D2ty3hUQFHPJa7A5zmMUMh9klXPCJn4bj58b1oxl08iC3/oTokLOOAh2Php0w/FujlXgVEg4oDX9JE0pfV+YIwwILB8aHuB1C8sYSdkWXHk0nYfM2bJNHSVt96e3ONHWmpyVXovKa5eDF/gc+sihtOx6mBqwdwVVrBH9nMWlUTlAnyKSEgSU3gf1U1iS6IkAhVCFjmBckMKj/Td0ayK2+Qh/0gToTjpoBE7H+o46Ix8pO2VxVt9hvBRkIjsFWfJWaGL+mj9ww7kR+B7BYbxPSoWD09olMGqMJQ+lPVwND/mU7S6XEfSglBLgvriRQ6Ysg1wOc19aQVGPN1Q4I4Bv7qcSRDubVXaRVxeCaDozYkdyWYUv3VHxbuSFOtlwUj4t6sCwqjKYvCsNP3hLZEemrM38tn+goMDl5a0UNJANMWFyaeni7LT3CTaWJNPLfk0fn6yoTUngsTJSk01MWvw/eDRWcJPHHoMkibDoJ13EOHISgUIBV2HfCuuvZTa/d6c/TSKw5oKxGxgyi4U5kaEaX3NX2a/6cLS3Ishxm9f+g+4cFfZlQh1wCm+S1FhWfBe+Q0qVwtJZJg5mSgF6sTcyKlem5Ib3qdho7t+9fZ4Qhy7ZUPIweL/y3HIiOldwH2CW9hSm69S/aWEmRAjcF1m/juKA="
    package_glob: *.deb
    dist: "raspbian/jessie"
    on:
      tags: true
